---
title: "Jacobi and stuff"
author: "Lawson Busch"
date: "2/22/2018"
output: html_document
---

```{r}
# Vector norm
vnorm = function(v,p=2) { 
  if ( p =="I") {
    return(max(abs(v)))
  }
  else {
    return(sum(abs(v)^p)^(1/p))
  }
}
```

```{r}
# Solves Ax = b iteratively using the Jacobi Method
# m is the maximum number of iterations: default m = 25
# p is the p value of the matrix norm
# tol is the stopping tolerance (using the relative residual norm on the backward error)
jacobi = function(A,b,m=25,x = rep(0,n),p=2,tol=0.5*10^(-6),history=FALSE) {
  n = length(b)
  if (history) {
    hist = matrix(NA,nrow=length(b),ncol=(m+1))
    hist[,1] = x
  }
  d = diag(A)
  R = A
  R[cbind((1:n),(1:n))] = 0  # allows for r to be sparse  
  steps=0
  for (j in 1:m) {
    x = (b - R %*% x)/d  #Vector use here makes in O(n^2) for matrix vector multiplication
    #implies better than n^3 for small number of iterations
    steps = steps+1
    if (history) {hist[,(j+1)] = as.matrix(x)}
    if (vnorm(b-A%*%x,p) <= vnorm(b,p)*tol) break 
  }
  if (history) return(list(x=x,iterations=steps,history = hist[,1:(steps+1)]))
  else return(list(x=x,steps=steps))
}


```

```{r}
A = cbind(c(5, 1), c(2, -4))
b = c(16, 10)
solve(A, b)
```

```{r}
jacobi(A, b)
```

Matrix 2:

```{r}
A1 = cbind(c(1, 5), c(4, -2))
b1 = c(11, 11)
solve(A1, b1)

jacobi(A1, b1)
```

Quadratic forms function
```{r}
#This results in a return quadratic function
f = function(A, b) {
  quadratic = function(x) {
    y = 0.5*t(x)*A*x-t(x)*b
    return(y)
  }
  return(quadratic)
}


```

